### ISSUE TITLE
Meson Build

### ISSUE THREAD

**Issue by PMaynard** [boothj5/profanity#1002]
Hello, 

Is this interest in replacing the current build system with meson [1]?

There are a number of advantages, the first being it supports reproducible builds. (Currently not sure if profanity is, anyone know?) It will ease cross-compiling, and has multi-platform support. 

Any thoughts?

[1] http://mesonbuild.com/

**Comment by Redfoxmoon3** [comment]
Reproducible builds have nothing to do with what build system you use, autotools is perfectly fine for that. IMO meson also makes cross compilation far worse.

**Comment by pasis** [comment]
Build system is a tool for developers. And they should use a tool they are familiar with. Because project can't rely on external contributions on every change that should be reflected to build scripts.

Also changing the build system has negative impact: modern build systems don't exist on exotic OSes/environments; many external projects rely on current build scripts and can't be changed in short term.

Also as topic related suggestion, don't add multiple build systems to the project.

**Comment by jubalh** [comment]
Totally agreed.

Meson has nothing to do with reproducible builds.
Maybe checking out https://reproducible-builds.org/ and seeing which packages in Debian (for example) are reproducible, only a fraction of those uses meson.

**Comment by vit1251** [comment]
@PMaynard I also dive into the fact that the autotool scripts do not work well on the new version Debain distribution #1590. If you have a proof of concept for meson, I would happy to join to your fork for testing and support.
