### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [boothj5/profanity#1034]
It is possible to migrate this repository to an organization (like other profanity)?
- https://help.github.com/articles/converting-a-user-into-an-organization/
- https://help.github.com/articles/about-repository-transfers/

**Comment by jubalh** [comment]
Why?

**Comment by Neustradamus** [comment]
It will be more professional ^^
And for have new devs too...

**Comment by jubalh** [comment]
> It will be more professional ^^

This is nonsense. Why should a organization be more professional?

>  And for have new devs too...

What do you mean with that? Especially devs that are totally new to profanity should use pull requests. Everybody else can use pull requests too, whats wrong with it?

If you were under the impression that an organization is needed to grant commit access to master branch you were wrong. To my knowledge there are currently at least three people who are able to merge pull requests, commit to master etc.

That being said, I thought about this some weeks ago, but since we have now several people with commit access I don't see a need for it.

**Comment by Neustradamus** [comment]
-> https://help.github.com/en/articles/differences-between-user-and-organization-accounts

**Comment by jubalh** [comment]
Dude, can you stop posting links and answer the questions?

I'm aware what organizations are. If you would have taken the time to click on my profile you would have seen that I'm in several organizations.

I'm closing this.

**Comment by Neustradamus** [comment]
@jubalh: I have forgotten to reply you here, thanks for the change.

**Comment by jubalh** [comment]
The change had nothing to do with this issue though. It was discussed already before the issue was opened but at this time it was decided that it's not needed. Then some things changed in private lives and we decided the an organization was needed from then on.
