### ISSUE TITLE
Make 'make dist' etc work

### ISSUE THREAD

**Issue by jubalh** [boothj5/profanity#1038]
Discussion started in https://github.com/boothj5/profanity/issues/1037

```
make dist
make  dist-gzip am__post_remove_distdir='@:'
make[1]: Entering directory '/home/michael/src/proftest/profanity-0.6.0'
make  distdir-am
make[2]: Entering directory '/home/michael/src/proftest/profanity-0.6.0'
make[2]: *** No rule to make target 'configure-debug', needed by 'distdir-am'.  Stop.
make[2]: Leaving directory '/home/michael/src/proftest/profanity-0.6.0'
make[1]: *** [Makefile:2145: distdir] Error 2
make[1]: Leaving directory '/home/michael/src/proftest/profanity-0.6.0'
make: *** [Makefile:2222: dist] Error 2
```

**Comment by pasis** [comment]
`configure-debug` is required for `make dist`, because it's mentioned in `script_sources` (see `Makefile.am`). You must be run `make dist` command from a directory, where you have removed the file.

---

List of files that have to be included in tarballs, but missed in `make dist` right now:
```
apidocs/         -- All the directory
profanity.spec   -- How to build RPM
theme_template   -- Template for themes
```

List of files under question (do we need to include them?):
```
configure-debug
configure-plugins
RELEASE_GUIDE.md
prof.supp         -- Valgrind file
```

@jubalh verify the lists above please.

**Comment by jubalh** [comment]
I would not add profanity.spec, it's only relevant for rpm based distros, and probably they already have their own spec, or used the one from here to build their own spec.

Non rpm distros also wouldn't need it, and its also deleted in the [release guide](https://github.com/boothj5/profanity/blob/master/RELEASE_GUIDE.md).

The rest I agree with you. And also about the spec file I don't have strong opinions, so we could include it too, just in case it's useful to someone.

**Comment by pasis** [comment]
@jubalh , `make dist` works now. I also updated RELEASE_GUIDE.md to describe how to generate tarballs automatically rather than manually. Please, check 0f0659aa091ac78cbdf5a04084bda17b80469a8e . The guide looks more simple now and doesn't require to clone or copy Profanity repository. Everything is done in your working tree. No need to clean anything, etc.

**Comment by jubalh** [comment]
@pasis great! Thank you!
