### ISSUE TITLE
Use OMEMO by default

### ISSUE THREAD

**Issue by philipflohr** [boothj5/profanity#1040]
Once #1039 is merged (@paulfariello great work, many thanks for your efforts!), I think it would be great if profanity would default to OMEMO messaging.

This includes to automatically run `/omemo gen` if necessary and run `/omemo start buddy@example.org` automatically as soon as a conversation is started.

If OMEMO messaging is not available on the own server or the remote server profanity should indicate that the session is not using OMEMO (like as an example Conversations does).

Additionaly I'd suggest to implement the possibility to manually stop the omemo encryption in order to communicate with clients without OMEMO support.

**Comment by jubalh** [comment]
I'm not a big fan of this idea.

Conversations tries to make onboarding to XMPP easy. They also enable OMEMO by default assuming that users want/need encrypted transfer.

I think profanitys users know what they want and can disable or enable it. Personally I know some people who prefer having PGP encrypted conversations over OMEMO encrypted ones. Different encryption methods suit different use cases.

I would like that profanity stays like it is and one can choose to enable whichever encryption one desires.

**Comment by kaffeekanne** [comment]
As much as i like e2ee, i agree with with not enabling any e2ee as default. But how about some indicator in the top bar. There is `[online]` and `[TLS]` already.

**Comment by philipflohr** [comment]
@kaffeekanne I'd appreciate any kind of visual feedback. One could add PGP and OTR, too.
To keep things optically clean this could be optional and be toggled using the settings.

@jubalh What do you think of automatic OMEMO available but disabled by default?

**Comment by paulfariello** [comment]
Having a preference or a policy for enabling omemo by default would be great in fact.

**Comment by dereckson** [comment]
I've the feeling any user with knowledge and able to make an educated decision about "let's use PGP instead of OMEMO" will have a more easy road to disable it and switch to the other option, than a person not aware of the different XMPP PEP.

Furthermore, to assume any user wishes to encrypt connections seems to be coherent with the current expected minimal set of features. It eases adoption and onboarding.

**Comment by jubalh** [comment]
> @jubalh What do you think of automatic OMEMO available but disabled by default?

What do you mean by this? It will always be available if profanity is build with the right flags, like PGP and OTR too.

> Having a preference or a policy for enabling omemo by default would be great in fact.

Surely we can have that.

**Comment by iNPUTmice** [comment]
> I think profanitys users know what they want and can disable or enable it.

I used to think that as well so believe me I totally understand where this is coming from.

This isn’t about *not knowing* this is about *forgetting* to. Assuming profanity, like other clients (Gajim, dino, Conversations), remembers the per conversation setting and over time you enable that for the vast majority of your conversations, new conversations (with newly added people) will be a rare exception and you will simply forget to enable OMEMO for that conversation as well. Humans are not good at paying attention to things that happen very infrequently.

On the other hand I have also learnt that there is a not insignificant user base on XMPP who are simply not allowed to encrypt for compliance reasons for example. So a global switch that changes the default like Conversations does is definitely in order. I don’t have any strong feelings on whether that switch should be on or off by default but the existence of that switch should be well documented because I believe - for the reasons described above - both sides of the OMEMO spectrum will have strong reasons to set it.

**Comment by kaffeekanne** [comment]
So after fiddling around with #1039 a lot recently i noticed, that i forget to enable omemo often. So something should be done as soon as omemo works stableish. Gajim does not enforce omemo by default, like conversations, but gives enough visual feedback in my opinion. So on new chats, one could decide to go omemo, but then the state should be remembered. I for sure keep forgetting to start omemo a second time.

**Comment by jubalh** [comment]
After the merge of https://github.com/boothj5/profanity/pull/1039 it is like this:
Once you started a OMEMO session with a contact, the next time you launch profanity it will remember that you talked with that contact over OMEMO and it will enable it again.

Now what @philipflohr wants is probably that we auto enable OMEMO for all 1:1 conversations if a certain setting is set.

**Comment by paulfariello** [comment]
The current exact behavior is that OMEMO is enabled as soon as you trust one of the fingerprint of a given contact.
So:
```
/omemo trust alice@bob.org <fingerprint>
/msg alice@bob.org
```
Would start an OMEMO encrypted chat.

**Comment by kaffeekanne** [comment]
State of OMEMO used in MUCs is not remembered at the moment.

**Comment by jubalh** [comment]
We thought about having a OMEMO policy with three options:

*Manual*
OMEMO is enabled manually.

Example:
```
/omemo start romeo@montague.lit
*** encrypted messages ***
/close
/msg romeo@montague.lit
*** cleartext messages ***
/close
```

*Automatic*
OMEMO is enabled once per contact and remembered.

Example:
```
/omemo start romeo@montague.lit
*** encrytped messages ***
/close
/msg romeo@montague.lit
*** encrytped messages ***
/close
/quit
/msg romeo@montague.lit
*** encrypted messages ***
/omemo end
/close
/msg romeo@montague.lit
*** cleartext messages ***
```

*Always*
OMEMO is always enabled, for every contact. Until explicitly disabled for that contact.

```
/msg romeo@montague.lit
*** encrypted messages ***
/msg someonewithoutomemosupport@montague.lit
 ! Your contact does not support OMEMO. Message has not been sent.
/omemo stop
/msg someonewithoutomemosupport@montague.lit
*** cleartext message***
 ```

**Comment by kaffeekanne** [comment]
Sounds good. How does OTR and PGP function in profanity. Keeping the behaviour of the now three E2EE in sync is important.

**Comment by philipflohr** [comment]
I think @jubalh s proposal is exactly what I'd expect profanity to do. If OTR/PGP behaves different, I'd suggest to change them to this behavior.

**Comment by jubalh** [comment]
@philipflohr feature is implemented now!
If you could checkout master and try it out it would be awesome to make sure everything is as expected.

**Comment by philipflohr** [comment]
You guys are making console messaging great again;)
Tested for some minutes and works great.
