### ISSUE TITLE
User defined notifications

### ISSUE THREAD

**Issue by pesla** [boothj5/profanity#455]
First of all: I was amazed to see a console based XMPP client this sophisticated. Nice work!

It would be great to be able to trigger a notification based on a string that I can define myself. For example:  `/notify trigger add beer` would cast a notification if I receive a message containing the word "beer". This command could be accompanied by `/notify trigger list` and `/notify trigger remove`.

**Comment by boothj5** [comment]
I've added a number of additional notification options, including a `/notify trigger` command.

I know this was requested a year ago but if you want to try it out, let me know your thoughts. Currently the triggers are only used by chat rooms and not regular chat, since I imagine you wouldn't want to filter out message notifications in a one to one conversation.

There are quite a number of options added (see `/help notify`), in summary for chat room triggers:

Global settings used for all chat rooms:
```
/notify room mention on|off 
/notify room trigger add <trigger>
/notify room trigger remove <trigger>
/notify room trigger list
/notify room trigger on|off
```
When in a chat room (due to #604 also being implemented) you can override the notification settings for that specific room using:

```
/notify on|off
/notify mention on|off
/notify trigger on|off
```

I found this useful as for some rooms I always want to know about new messages, but others I want to only know when my nick is mentioned or some specific triggers are found in a message.

Whilst in a room, you can see the settings for that room (either global or room specific) by just calling:

```
/notify
```

Currently the actual triggers are global, i.e. you cannot set triggers per room, this would be quite a bit more work and not sure how much it would be used.

Finally, if the `/notify remind` setting is enabled, you will only get reminder notifications if a message triggered a notification, e.g. if you receive 10 messages and none of the settings resulted in a notification being triggered for any of them you'll get no reminder notifications. If the next message triggers a notification, reminder notifications will also start to appear with the total message count (11).
