### ISSUE TITLE
Contact incorrectly showing as offline when has capital letters in JID (Gtalk)

### ISSUE THREAD

**Issue by nick-orton** [boothj5/profanity#506]
Running profanity verision 0.4.5 on OSX 10.9.5

I am connecting to GTalk.  I have a contact that has capital letters in his jid.  Adding him to the roster persists the name with lower case letters.  I assume that jids are case insensitive.  However, this contact does not show as online even when he is.  I don't know if this is a bug in GTalk's implementation of jabber or is a bug in profanity.  Other chat clients do not have this issue. 

Explicitly Doing 
    /msg Contact.With.Caps@gmail.com
correctly shows the contact's status in the chat window

Doing
    /msg contact.with.no.caps@gmaill.com
shows the contact as offline

Doing
    /msg contacts-nick
shows the contact as offline because it uses the lower-cased version of the jid

**Comment by nick-orton** [comment]
Similar issue with Caps

    /roster add CapGuy@gmail.com
    /roster nick CapGuy@gmail.com foo
    "Contact not found in roster: CapGuy@gmail.com"

**Comment by boothj5** [comment]
I think I've fixed this now in master.

It is valid for JIDs to contain mixed case, but all comparisons should be case insensitive which means the bug is in profanity.

The current fix means that when adding a contact to your roster, the JID will always be lowercased, even if it contains mixed case.

If you have time, let me know if the latest code from master works for you, and whether normal messaging etc still works correctly.

Thanks.
