### ISSUE TITLE
"received an encrypted message but no private connection is established"

### ISSUE THREAD

**Issue by quite** [boothj5/profanity#550]
I occasionally get this message. I don't know the xmpp/otr protocol well at all, but, would it be possible to display the jid that this message came from? ... or not at all?

**Comment by boothj5** [comment]
I've made a small change in master which should show the contact's jid before the message (when displayed in the console rather than a chat window).

Let me know if this works for you.

**Comment by quite** [comment]
Cool. Then I may see which clients profanity's otr interoperability is weak.
Because I do have certain problems with that.

**Comment by quite** [comment]
So, today I got this "received an encrypted message..." with the jid of a friend with whom I didn't talk today. But I did yesterday, using OTR. Since then, I have restarted my profanity a couple of times. So apparently, my friend's client doesn't understand when a OTR session is finished, or has timed out, or however such things are dealt with...

Does profanity do something special to detect this kind of situation? My friend is using emacs-jabber with https://github.com/legoscia/emacs-jabber-otr . I'll open a ticket over there and reference this one.

**Comment by quite** [comment]
Perhaps, profanity should renegotiate an OTR session when this happens? And/or notify the other jid somehow, not to lose messages...

**Comment by boothj5** [comment]
OTR requires that both parties are online to enable a secure session since the encryption mechanism only lasts for the duration of that session. So when one or the other client disconnects/closes a window etc, the session should be ended at both ends.

If one person sends a message after the session has been closed, it should be sent unencrypted, since the other end will never be able to decrypt it.

I'm not sure there's much that can be done at the profanity end, however if any suggestions come from the related issue emacs-jabber-otr, let me know.

Thanks.

**Comment by boothj5** [comment]
Closing this issue for now as I don't think much can be done at this end.

If something comes out of the related issue that could be changed in profanity, I can reopen.
