### ISSUE TITLE
Compilation error because of missed include stdlib.h

### ISSUE THREAD

**Issue by pasis** [boothj5/profanity#561]
Hello, I tried to build the latest master on my virtual machine with Gentoo and got error:
```
src/event/client_events.c: In function ‘cl_ev_connect_account’:
src/event/client_events.c:58:5: error: implicit declaration of function ‘free’ [-Werror=implicit-function-declaration]
src/event/client_events.c:58:5: error: incompatible implicit declaration of built-in function ‘free’ [-Werror]
src/event/client_events.c: In function ‘cl_ev_send_msg’:
src/event/client_events.c:80:5: error: incompatible implicit declaration of built-in function ‘free’ [-Werror]
```
To build it I made change:
```
--- a/src/event/client_events.c
+++ b/src/event/client_events.c
@@ -32,6 +32,7 @@
  *
  */
 
+#include <stdlib.h>
 #include <glib.h>
 
 #include "config.h"
```

**Comment by boothj5** [comment]
I've added the include.

I guess somehow my build is picking up the header from another include, Are you aware of a way to enforce more strict include checks, ensuring that source files needing them include them directly rather than picking them up transitively?

Oh, and good to hear from you, been a while!

**Comment by pasis** [comment]
I don't know such a way for gcc and I think this is work for a static analysis tool.

Thanks for the fix.
