### ISSUE TITLE
OTR key generation shows error when terminal resized

### ISSUE THREAD

**Issue by boothj5** [boothj5/profanity#562]
Start OTR key generation with `/otr gen`, and then resize window, the following error is displayed:

```
select() error: Interrupted system call
```

On Awesome Window Manager, the key generation still eventually completes and the error disappears.  At the very least, hide or prevent the error message being displayed.

**Comment by pasis** [comment]
Seems it's not a problem at all. This message is printed by libgcrypt's function random/rndlinux.c:_gcry_rndlinux_gather_random(). When select() returns error this function prints message and calls select() again. Resizing terminal generates a signal and as results function select returns error EINTR if it is blocked.

You can try to play with gcry_set_log_handler() and set your own handler to print such messages to file instead of stderr (or ignore).
