### ISSUE TITLE
PGP Manually add public key for a JID

### ISSUE THREAD

**Issue by PMaynard** [boothj5/profanity#570]
Unable to to start secure PGP communications with a user whose JID is not the same as their PGP address. Though PGP will work if someone starts PGP with you. As in I can see their fingerprint listed and PGP is shown in the title bar.

For example, JUID = osaka@matrix.ac and PGP = osaka@email.com, you'd not be able to start PGP with this user as the PGP agent has osaka@email.com not osaka@matix.ac.

What macabber does is allow you to assign a public key to a user. 

[From Mcabber User Guide](http://mcabber.com/files/mcabber_guide.pdf)
> If you happen to have a contact whose Jabber client doesn't conform to that
>part of the standard, you can manually give mcabber their key finngerprint:
> pgp   setkey   foo@bar.net   D9940C9BB1B92310

**Comment by PMaynard** [comment]
This needs more testing, I feel that my test was not complete as OTR may have been causing issues.

**Comment by boothj5** [comment]
I'll add public key assignment, I guess it's a very common use case.  Will keep this issue updated.

**Comment by boothj5** [comment]
Just tested with a user who's PGP address is an email address rather than their JID, and encryption works when initiated both ways 

The workaround in Mcabber I believe is for when your contact doesn't sign their presence (as mentioned in the spec - http://www.xmpp.org/extensions/xep-0027.html#signing), so Profanity (or Mcabber) cannot determine the key to use when encrypting messages.

However, this is a SHOULD rather than a MUST in the spec, so the manual assignment will still be useful and I'll add it.

Did you have any more luck with the OTR/PGP conflicts?

Thanks.

**Comment by boothj5** [comment]
I've added the extra command in master, similar to Mcabber:

```
/pgp setkey <contact> <keyid>
```
Similar to OTR, this is a per account property, and will saved between profanity sessions at:

```
~/.local/share/profanity/pgp/<account_dir>/fingerprints
```

Any signed presence from the contact will override this setting in memory, but the persisted value will remain.
