### ISSUE TITLE
Segfault when joining a channel and pressing delete

### ISSUE THREAD

**Issue by JD557** [boothj5/profanity#595]
Hi,

I just noticed that if I launch profanity, join a channel and press delete, I get a segfault.
(pressing ctrl+D instead of delete seems to have the same effect)

Any ideas on what may be causing this? Can you also reproduce this?

**Comment by boothj5** [comment]
Can't currently recreate, what's your OS and Terminal?

**Comment by JD557** [comment]
OS: Mac OS X 10.10.3
Terminal: iTerm2 2.1.1

**Comment by boothj5** [comment]
Thanks for the info, I can confirm I see the same issue in 0.4.6 (on both OSX and Linux).

The latest code in master replaces the input handling code with GNU Readline, and the problem has gone away.

Closing this issue as it will be fixed in the next release.  If you see the behaviour again, let me know.
