### ISSUE TITLE
SSL: Force TLS on all connection, show warning when in plaintext.

### ISSUE THREAD

**Issue by boothj5** [boothj5/profanity#616]
As per the comment by @PMaynard at #280 :

- Force TLS on all connection, show warning when in plaintext.
- Add option in accounts to enable TLS; Don't allow STARTTLS to drop down to plaintext if option is enabled. If not enabled, keep current opportunistic mode.

**Comment by pasis** [comment]
You can use new function for this: strophe/libstrophe@b7fbc81740142320782cfbcdda8fe14c1ea804cd

Example is here: https://github.com/WorksSystems/wks_xep0047/blob/master/source/xmpp_helper.c#L32

**Comment by boothj5** [comment]
An indicator has been added to the titlebar `[TLS]` which is coloured similar to the encryption indicators for OTR and PGP.

The indicator is enabled by default and can be enabled/disabled with:

```
/tls show on
/tls show off
```

The console will also show a message when a login is performed without TLS. This covers the first point.

The second point needs a little more work, I believe at the moment that libstrophe doesn't allow for the process of falling back to plaintext to be stopped.  The connection can be cancelled after the login was performed, but I think by this stage it's too late as credentials have already been sent.

I think if the STARTTLS feature is not received with the stream features, and the application has somehow specified TLS as being mandatory, then the login should be stopped at this point, and the application informed. @pasis correct me if I'm wrong here.

**Comment by pasis** [comment]
When server doesn't send starttls and tls is mandatory libstrophe will close connection and application's callback will be called. So your point is correct.

Just for information: libstrophe doesn't try to use plaintext if tls fails, so then only way to get plaintext connection is when server doesn't send starttls (or application disabled tls at all).

I still don't know how interface should look. It could be another `xmpp_conn_set_mandatory_tls()` or `xmpp_conn_set_flags()`. The last one receives ORed flags like XMPP_CONN_MANDATORY_TLS, XMPP_CONN_LEGACY_SSL, XMPP_CONN_DISABLE_TLS and any future flags.

**Comment by boothj5** [comment]
I like the sound of the second option - OR'd flags for TLS connection options, I guess it makes it easier to add new settings if needed.

Are you planning to do anything like this in libstrophe? If not, no problem I will look into it, just want to make sure we're not duplicating effort.

Cheers.

**Comment by pasis** [comment]
Yes, this function is already in my TODO list. I want to get new stable API before new version of libstrophe. And freeze it until the next major version.

I'm thinking about increasing major version to 0.9.0 for the next stable release, because I've already added some new functions to API and am planning to add new ones.

**Comment by pasis** [comment]
prototype: strophe/libstrophe@fe2ce0ad4c8630f9f8c31d036927a03e6c1d59c1
Please, comment if you see any problems/typos/etc.

**Comment by boothj5** [comment]
Can't see any issues.

One question, is there a way for the application to find out why the connection was disconnected (for example: because of the lack of TLS support from the server)? I originally thought a callback, but that's probably unnecessary, maybe just some error code check? I could be missing something that's already there.

**Comment by pasis** [comment]
On disconnection libstrophe calls handler:
```
    /* fire off connection handler */
    conn->conn_handler(conn, XMPP_CONN_DISCONNECT, conn->error,
                       conn->stream_error, conn->userdata);
```
And conn->error would be the correct thing to check IF libstrophe had unified error codes. Since this argument can hold even tls implementation-specific codes, there is no proper way to handle disconnection errors.
I didn't set conn->error when connection isn't secured just because of the above problem. But I can set it to some errno code, like EPERM (EPROTO or ENOPROTOOPT would be better, but I'm afraid not all systems define them).

Correct solution would be to re-write most libstrophe's functions and pass errors from the top to the bottom. And maybe define own set of error codes, since different systems can have not full list of errno codes. But this is long task.

P.S. page with all error codes: http://www.virtsync.com/c-error-codes-include-errno

**Comment by boothj5** [comment]
Ok, that makes sense.  I guess it not a massive problem, since the most important thing is that the application just knows that the connection was unsuccessful.

**Comment by pasis** [comment]
`xmpp_conn_set_flags()` is in master: strophe/libstrophe@182803926beef4cc2e0fe4928e61c8ce0d969f26

**Comment by boothj5** [comment]
This has now been implemented in master. By default TLS is mandatory for all connections.

To change the setting when connecting without an account, use the `tls` property, which can be one of `force`, `allow`, `disable`:

```
/connect me@myserver.org tls disable
```

The setting will be saved with the newly created account (see `/accounts show <account>`). To change the setting for a particular account:

```
/account set me@myserver.org tls allow
```

As a result of this change, the `--disable-tls` command line option has been removed.
