### ISSUE TITLE
Generate UUIDs with alternative libraries

### ISSUE THREAD

**Issue by boothj5** [boothj5/profanity#644]
Raised at the mailing list: https://groups.google.com/forum/?hl=en-GB#!topic/profanitydev/SieTZLttXQk

Some systems do not have `libuuid` available, check for alternative libraries in `configure.ac`

**Comment by pasis** [comment]
What do you think about API `void xmpp_uuid_gen(ctx, buf, len)` or `char *xmpp_uuid_gen(ctx)`? Since usage of UUID is described in RFC and XEP it could be a part of libstrophe.

UUID version 4 from [RFC4122](http://tools.ietf.org/html/rfc4122) can be implemented easily and will be platform-independent.

**Comment by boothj5** [comment]
Would be nice to have the feature in libstrophe, one less library is always a good thing.

**Comment by pasis** [comment]
libstrophe has xmpp_uuid_gen() now: strophe/libstrophe@8627fbb13fc0d929f54eb094f947fe0752bd33e0
You can use it after switch to libmesode or make a choice among libuuid and new libstrophe in configure.ac. As I saw, many distros still contain libstrophe-0.8.7.

**Comment by boothj5** [comment]
Thanks, I've changed Profanity to use this function, tested, and removed the dependency on libuuid.

I'll just add the version of libstrophe/libmesode required in the release notes, since it seems most distros upgrade libstrophe when it is required by a Profanity release.
