### ISSUE TITLE
[Feature Request] Add "/subject append"

### ISSUE THREAD

**Issue by pheerai** [boothj5/profanity#661]
Quite often, I'd like to just append something behind the currently set MUC-subject. For this, it would be nice to have a "/subject append" command.

I don't consider this important, not even necessary, though, only a "nice-to-have"-feature.

**Comment by boothj5** [comment]
Since this was a fairly simple change I've added it to master.  It also made me think `/subject prepend` and `/subject edit` would be useful so added these too.

See `/help subject`

Autocomplete for `/subject edit` will populate the current room subject in quotes so you can edit it. For example if the current subject is "Welcome to the room", the following:

```
/subject e<tab>
/subject ed<tab>
/subject edi<tab>
/subject edit<tab>
/subject edit <tab>
/subject edit "<tab>
```

Will all result in:

```
/subject edit "Welcome to the room"
```
