### ISSUE TITLE
feature: somehow (optionally) indicate presence even when /roster by group

### ISSUE THREAD

**Issue by quite** [boothj5/profanity#665]
As the length of my roster increases, I will probably start using groups. But it would be nice to see presence at the same time...

**Comment by boothj5** [comment]
I've added some more options for configuring the roster display.  Including showing presence, status message, ordering by presence rather than alphabetically by name, showing the count of users in each group, and resource priority.

All settings are themable and can be set with the roster command (see `/help roster`).

I'm going to add a few more display options, such as the character prefixing each header (currently `-`), option to use one line for all information, or ability to choose where to start a new line, configurable indentation and ideally word wrapping.

In the meantime let me know if the current changes are enough for your needs.

**Comment by quite** [comment]
Yes, new functionality works fine. And the upcoming polish sounds promising. Thanks a lot.

**Comment by boothj5** [comment]
Additional features mentioned above have also now been added to master.
