### ISSUE TITLE
Bookmarks for Slack XMPP chat not persistent

### ISSUE THREAD

**Issue by sonictk** [boothj5/profanity#705]
Whenever I join a Slack channel and do:
`/bookmark`

profanity tells me that the bookmark has been saved, and when I list it with `/bookmark list` it shows up. However, after quitting and re-starting profanity, I am not auto-joined into those channels, and the bookmarks have disappeared.

The bookmarks seem to work for Hipchat, though, so I'm wondering what the issue might be. In profanity.log, I see the following:

```
07/01/2016 08:43:44: prof: INF: Connecting using account: sonictk@tds-anonymous
07/01/2016 08:43:44: prof: INF: Connecting as sonictk@tds-anonymous.xmpp.slack.com/.xmpp.slack.com
07/01/2016 08:43:45: prof: INF: Loading OTR key for sonictk@tds-anonymous.xmpp.slack.com
07/01/2016 08:43:45: prof: INF: No private key file found /home/sonictk/.local/share/profanity/otr/sonictk_at_tds-anonymous.xmpp.slack.com/keys.txt
07/01/2016 08:43:45: prof: INF: No fingerprints file found /home/sonictk/.local/share/profanity/otr/sonictk_at_tds-anonymous.xmpp.slack.com/fingerprints.txt
07/01/2016 08:43:45: prof: INF: sonictk@tds-anonymous.xmpp.slack.com logged in successfully
07/01/2016 08:43:45: prof: ERR: IQ error received, id: bookmark_init_request, error: Not implemented
07/01/2016 08:46:38: prof: INF: Received diso#info response for room: general@conference.tds-anonymous.xmpp.slack.com
07/01/2016 08:46:38: prof: ERR: IQ error received, id: prof_room_disco_info_5, error: Unrecognized request
07/01/2016 08:46:40: prof: ERR: IQ error received, id: prof_bookmarks_update_6, error: Not implemented
```

But it doesn't make sense how my Hipchat bookmarks work fine though?

Any advice on resolving this issue would be greatly appreciated!

**Comment by boothj5** [comment]
Because Slack uses an XMPP gateway it's probably only supplying the bare minimum XMPP functionality to allow for chat, the log shows that many features are not supported.

I assume HipChat also uses a gateway, but probably offers more functionality.

I used Slack at my previous company and bookmarks would not work, as a workaround I did the following:

1) Create a script `slackrooms` and place it in `~/.local/share/profanity/scripts/`. The script should contain commands to join all rooms you wish to join when connecting:

```
/join room1@conference.[company].xmpp.slack.com
/join room2@conference.[company].xmpp.slack.com
/join room3@conference.[company].xmpp.slack.com
```

2) Set this as the `startscript` property for your Slack account using the `/account` command:

```
/account set [name]@[company].xmpp.slack.com startscript slackrooms
```

Then when connecting the rooms are joined.

The script functionality is only available in master and will be out in the next release (0.5.0) so if you want to try this you'll need to build the latest code: http://www.profanity.im/install.html#manualinstall

**Comment by sonictk** [comment]
Hi @boothj5 , I tried building profanity from source, but I'm getting the following issue (CentOS 7 x64)

`configure: error: Neither libmesode or libstrophe found, either is required for profanity`

I already compiled libstrophe from source and installed it as per the documentation here without issues:

https://github.com/strophe/libstrophe

And in my `/usr/local/lib` I have the following binaries:

`libpython3.3m.a  libstrophe.a  libstrophe.la  libstrophe.so  libstrophe.so.0  libstrophe.so.0.0.0  pkgconfig  python3.3`

So I assume the installation of libstrophe isn't the issue...is there a way I can check why the profanity configure script can't seem to find libstrophe?

Thanks!

**Comment by boothj5** [comment]
I think the following when running `./configure` during the libstrophe build will fix the issue:

```
./configure --prefix=/usr
```

**Comment by boothj5** [comment]
Closing as the no persistent bookmarks is due to the Slack XMPP gateway
