### ISSUE TITLE
Missing Declaration in src/plugins/api.c

### ISSUE THREAD

**Issue by femnad** [boothj5/profanity#747]
Hello,

Current HEAD (9d31ce4) fails during compilation because of a missing include in `src/plugins/api.c`:
```
src/plugins/api.c: In function ‘api_register_command’:
src/plugins/api.c:119:9: error: implicit declaration of function ‘strdup’ [-Werror=implicit-function-declaration]
         help->synopsis[i] = strdup(synopsis[i]);
         ^
src/plugins/api.c:119:29: error: incompatible implicit declaration of built-in function ‘strdup’ [-Werror]
         help->synopsis[i] = strdup(synopsis[i]);
                             ^
src/plugins/api.c:123:18: error: incompatible implicit declaration of built-in function ‘strdup’ [-Werror]
     help->desc = strdup(description);
```

I think `string.h` should be included in `src/plugins/api.c`.

**Comment by boothj5** [comment]
Thanks for pointing it out... I'm still trying to find a way to configure my compiler to fail on these errors, at the moment it continues and compiles.

I'll fix later when I have a moment.

**Comment by femnad** [comment]
Yes, after inspecting the `configure.ac` file I realize that the `-Werror` flag is active only when the `PACKAGE_STATUS` is defined as `development`, which is the case for a git clone, but not the tarball release. So, this is observable only when compiling from a git clone and making the compilation run successfully is easy enough via modifying `src/plugins/api.c` or the autoconf script.

**Comment by pasis** [comment]
To get this error you need to build profanity without otr support:
```
./configure --disable-otr
make
```
Seems string.h is included in otr-specific headers.

**Comment by femnad** [comment]
Yep, you're right, I don't have `libotr` installed so otr functionality is disabled automatically.

**Comment by boothj5** [comment]
The issue I have seen before is slightly different: 

On most linux distros, headers are picked up transitively via other headers that are included directly, whilst on Cygwin I always get an explicit error on compile unless the header is included directly in the file being compiled.

I was wondering if there is a way to force the compiler/preprocessor to be as strict as possible i.e. only use headers defined in the individual file being compiled.  So far I haven't found anything on this and I can't really see how it would work, since for compile to work, the headers must be included, meaning their headers will be included and so on.

I'm not sure why Cygwin works this way either.

**Comment by femnad** [comment]
OK, I see your point now. Having something like that would be useful, especially for continuous integration tests, however as you said I'm not sure how you would instruct a compiler to behave that way.

**Comment by incertia** [comment]
we just need `#define _GNU_SOURCE`

**Comment by boothj5** [comment]
Fixed this missing include.

I'll take a look at the Cygwin compilation behaviour separately.
