### ISSUE TITLE
Python Plugins: subscribe to PEP (/disco add) hook

### ISSUE THREAD

**Issue by ReneVolution** [boothj5/profanity#806]
Hey,

for the OMEMO plugin i am working on i need the ability to add 'urn:xmpp:omemo:0:devicelist+notify' to the users disco. See #658 

Thanks.

**Comment by boothj5** [comment]
Not sure if this is what you're after, but it's possible to manipulate the stanzas sent when disco info/disco items requests are received, using the [on stanza send hooks](https://github.com/boothj5/profanity/issues/772#issuecomment-201869520).

The following (from the `/xmlconsole`) shows what profanity responds with on disco info and disco items requests:

```
RECV:
<iq id="prof_disco_info_25" type="get" to="chanleemoon@jabber.org/profanity" from="boothj5@jabber.org/macmini">
  <query xmlns="http://jabber.org/protocol/disco#info"/>
</iq>

SENT:
<iq id="prof_disco_info_25" type="result" to="boothj5@jabber.org/macmini">
  <query xmlns="http://jabber.org/protocol/disco#info">
    <identity type="console" category="client" name="Profanity 0.5.0dev.master.559b160"/>
    <feature var="http://jabber.org/protocol/caps"/>
    <feature var="http://jabber.org/protocol/chatstates"/>
    <feature var="http://jabber.org/protocol/disco#info"/>
    <feature var="http://jabber.org/protocol/disco#items"/>
    <feature var="http://jabber.org/protocol/muc"/>
    <feature var="jabber:iq:version"/>
    <feature var="jabber:iq:last"/>
    <feature var="jabber:x:conference"/><feature var="urn:xmpp:ping"/>
    <feature var="urn:xmpp:receipts"/>
  </query>
</iq>
```

```
RECV:
<iq id="discoitemsreq" type="get" to="chanleemoon@jabber.org/profanity" from="boothj5@jabber.org/macmini">
  <query xmlns="http://jabber.org/protocol/disco#items"/>
</iq>

SENT:
<iq id="discoitemsreq" type="result" to="boothj5@jabber.org/macmini">
  <query xmlns="http://jabber.org/protocol/disco#items"/>
</iq>
```

So for example an implementation of `prof_on_iq_stanza_send()` could check for:
* type="result"
* query element with xmlns="http://jabber.org/protocol/disco#items"

Then add an item and return the updated stanza to be sent.

Again not sure if this is what you need, let me know.

**Comment by ReneVolution** [comment]
Hmm ... i'll give it a shot later. It might actually work.

Anyway, i guess this assumes that the plugin is loaded already before the disco events happen, right? Or before an Account connects?

**Comment by boothj5** [comment]
Actually I'm not sure this is enough, since it wont work with capabilities caching see http://xmpp.org/extensions/xep-0163.html#howitworks examples 4 and 5.

I guess some new API calls to add to service discovery information will be needed.  So when `prot_init()` is called we can call functions like:

```
prof_add_disco_feature()
prof_add_disco_item()
```

For example:

```
prof_add_disco_feature("urn:xmpp:omemo:0:devicelist+notify")
```

I'll look at adding these API functions.

**Comment by ReneVolution** [comment]
Yea, that was actually my initial thought.
Hope they are easy to add.

**Comment by boothj5** [comment]
Yeh, I get you now.

Should be fairly easy, gonna take a look shortly.

**Comment by boothj5** [comment]
Added the following  function to the API.

```
prof.disco_add_feature(feature)
```

The feature will be included in any subsequent disco info requests made to profanity.  The verification SHA1 hash sent on presence (to allow client feature caching at the server and other clients) is also updated.

If the user is connected when the plugin is loaded, the current presence is automatically resent with the updated SHA1 so any caches can be updated.

Example: [python-test.py](https://github.com/boothj5/profanity-plugins/blob/master/tests/python-test.py#L331)

Haven't added anything to add disco items, but I don't think you need it at the moment, plus it can be added with the on stanza hooks since it doesn't affect the verification string.  However if you find you need it or it'll make things easier just let me know.

**Comment by ReneVolution** [comment]
Great work. Thanks. So far it seems to work as expected.
