### ISSUE TITLE
Configure fails with self-built libstrophe on Arch Linux

### ISSUE THREAD

**Issue by moridius** [boothj5/profanity#809]
I built libstrophe myself (on Arch Linux) and then tried to build Profanity. The configure script fails like this:
> checking for libmesode... no
checking for libstrophe... no
configure: error: Neither libmesode or libstrophe found, either is required for profanity

Libstrophe is installed, but the script doesn't find it.
> $ whereis libstrophe 
libstrophe: /usr/local/lib/libstrophe.so /usr/local/lib/libstrophe.a /usr/local/lib/libstrophe.la

**Comment by boothj5** [comment]
Looks like the library search path doesn't have `/usr/local`.  One way to fix it would be to install libstrophe to `/usr` rather than `/usr/local`, i.e. when building libstrophe:

```
./configure --prefix=/usr
```

The other option is to add `/usr/local` to the library search path when running profanity's `./configure`, but I'm not quite sure of the right flags to pass.

**Comment by pasis** [comment]
Profanity uses `PKG_CHECK_MODULES` to find libmesode/libstrophe, so you need to configure PKG_CONFIG_PATH properly. I think this should be enough:
```
cd profanity
./configure PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"
```
