### ISSUE TITLE
Problem with Jabber delivery receipts (Gajim)

### ISSUE THREAD

**Issue by nd2s** [boothj5/profanity#829]
When using Gajim to talk to Profanity I see loads of read "X"s next to my messages. As far as I know this means Profanity announces that it supports sending delivery receipts but fails to actually send them. So Gajim thinks the messages weren't delivered successfully.

Edit: I don't know if Prosody supports this feature, but ideally it would send them instead of just stop announcing it can.

**Comment by boothj5** [comment]
Whilst Profanity supports requesting and sending receipts, they have to be enabled with the `/receipts` command.

**Comment by nd2s** [comment]
Good to know, but the issue still is relevant. If they are deactivated, Profanity shouldn't advertise the capability.

**Comment by nd2s** [comment]
There is another problem related to this: When requesting receipts is activated, Profanity is requiring them for every single contact no matter if that client can handle receipts or not. This is problematic when chatting to Adium users for example - every single message will stay red.

**Comment by boothj5** [comment]
I've added some changes:

**Advertising support**
* Profanity only includes this feature in its service discovery responses if it has been enabled with `/receipts send on`
* Whenever the setting is changed with `/receipts send on|off` a presence stanza is sent with the relevant SHA1 hash so other clients will be able to see the change.

**Sending receipt requests to other clients**
* Receipt requests are now only sent when Profanity knows for sure that the recipient supports them.
* This means that Profanity can only send receipt requests when at least one message has been received from the recipient (since only then we know the full jid and its capabilities)
* If the recipient disables receipts half way through a conversation, Profanity will no longer request them

If you have a chance to test, let me know your results.

**Comment by nd2s** [comment]
I just tested it: seems to work fine! No more problems. Thank you very much!

I think it would now make sense to activate receipts support by default (like Gajim does).

**Comment by boothj5** [comment]
Thanks for trying it out.

I usually keep additional features disabled by default, so the user gets minimal chat functionality, but can add extras that they want, different approach to Gajim.
