### ISSUE TITLE
Plugins install

### ISSUE THREAD

**Issue by KThand1** [boothj5/profanity#883]
Hi I have a FR,

If possible. 

Instead of typing out the file name for every plugin I wish to install can Profanity be given a path to a plugins directory, for example  and then install everything within that? 

Perhaps could also install based on extension (.py, .rb etc)

Thanks.

**Comment by boothj5** [comment]
Added some changes in master:

The `/plugins install` command now also accepts a directory as its argument, and will load all (Python and C) plugins found recursively in that directory:

```
/plugins install ~/projects-git/profanity-plugins/stable
``` 

Also added `/plugins sourcepath` command to set a default to use above rather than having to type the path each time, for example:

```
/plugins sourcepath set ~/projects-git/profanity-plugins/stable
``` 

From this point on you can just:

```
/plugins install
```

Also added the ability to  bulk enable/disable all plugins by not supplying arguments:

```
/plugins load
/plugins unload
```

**Comment by jubalh** [comment]
Relevant commits:
https://github.com/boothj5/profanity/commit/286fecf38d218d10366f025faf7cffcb425e19f4
https://github.com/boothj5/profanity/commit/5f1ba08f5500646fb92df8d4b9920eac987bc11a
