### ISSUE TITLE
[Plugins] Allow plugins send hooks to block outgoing messages

### ISSUE THREAD

**Issue by ReneVolution** [boothj5/profanity#890]
Currently, there is no way to block an outgoing message and worst case the unmodified message will just leave the messenger. This is especially bad for plugins that provide encryption.

**Comment by boothj5** [comment]
I'm thinking the best way to implement this is to change the behaviour of:

[`prof_on_message_stanza_send(stanza)`](http://www.profanity.im/plugins/python/html/plugin.html#plugin.prof_on_message_stanza_send)

Currently returning `None` will send the original stanza.

The change would be if `None` was returned the stanza will not be sent.  The user can still send the original by returning it, so this should suit all needs.

Let me know if this would work for you, and I'll make the change.

**Comment by boothj5** [comment]
Actually these two hooks would be a better place for the change, they're at a higher level so the plugin implementation wouldn't have to parse the stanza:

[prof_pre_chat_message_send(barejid, message)](http://www.profanity.im/plugins/python/html/plugin.html#plugin.prof_pre_chat_message_send)
[prof_pre_room_message_send(roomjid, message)](http://www.profanity.im/plugins/python/html/plugin.html#plugin.prof_pre_room_message_send)

**Comment by ReneVolution** [comment]
I would actually prefer the `prof_on_message_stanza_send(stanza)` option to return `None` if i need to. 

For some background:

I use the `prof_pre_chat_message_send(barejid, message)` to request the OMEMO bundle (encryption keys) to build a session on the first message (as recommended by the XEP). This gives me usually enough time before `prof_pre_chat_message_send(barejid, message)` will be called. Does this make sense?

Having the option available on both plugin hooks would leave the decision with the plugin developer and might be the best choice if feasible.

**Comment by boothj5** [comment]
I've updated the following as described above (returning `None` stops the message being sent):

[`prof_pre_chat_message_send(barejid, message)`](http://www.profanity.im/plugins/0.5.1/python/html/plugin.html#plugin.prof_pre_chat_message_send)
[`prof_pre_room_message_send(roomjid, message)`](http://www.profanity.im/plugins/0.5.1/python/html/plugin.html#plugin.prof_pre_room_message_send)
[`prof_pre_priv_message_send(roomjid, nick, message)`](http://www.profanity.im/plugins/0.5.1/python/html/plugin.html#plugin.prof_pre_priv_message_send)

After taking a look, modifying the behaviour of `prof_on_message_stanza_send(stanza)` would be a lot more complicated, since it is called from a very low level in the code, i.e. just before the XMPP library is used to send any message stanza.  Also since it is used for _any_ message stanzas, it is called from many places in profanity and all of them would need to handle plugins cancelling the stanza send.

In terms of timing, both `prof_pre_chat_message_send` and `prof_on_message_stanza_send`are called on the same event.  The `prof_pre_chat_message_send` is just higher up the call stack and only used for sending chat messages.  As mentioned above `prof_on_message_stanza_send` is much lower in the call stack and is used for any kind of message stanza.

Let me know your thoughts.

**Comment by boothj5** [comment]
@ReneVolution I'm going to close this issue as the message hooks have been changed and I need to get the 0.5.1 release out this week.  If you find you really need the stanza hook to be changed, we can raise a separate issue for 0.5.2.

**Comment by ReneVolution** [comment]
You are absolutely right. Whatever else i need to do should be handled within my code. Thanks.
