### ISSUE TITLE
Auto login?

### ISSUE THREAD

**Issue by Nic321** [boothj5/profanity#931]
How do I setup autologin or save credentials so I don't need to enter my uname:passwd every time I start profanity?

**Comment by Nomad145** [comment]
You can use `/account` to set a password for an account and `/autoconnect` to autologin that account.  See the following.

http://profanity.im/reference.html#account
http://profanity.im/reference.html#autoconnect

Note that you can also use `/account set my_account eval_password ...` to retrieve a password from a more secure source.  Otherwise, your account password will be stored in plaintext in `~/.local/share/profanity/accounts`.
