### ISSUE TITLE
Decrypt single OTR message?

### ISSUE THREAD

**Issue by teran-mckinney** [boothj5/profanity#940]
My client was offline when I received a message from a previously established OTR "connection". Is it possible to decrypt that message? If so, how?

Thank you!

**Comment by boothj5** [comment]
I don't believe this is possible as session keys are negotiated whilst both parties are online. as part of the "perfect forward secrecy" feature of OTR.

**Comment by teran-mckinney** [comment]
Hmm, that makes sense but it seems that the sessions are generated with the same session key each time.

If I disconnect and reconnect then run /otr start, they don't see that anything has changed. I wonder if by chance there's a bug in the implementation where session keys are not rotated and can be predicted.

**Comment by boothj5** [comment]
In OTR the session keys are transparent to the user, I believe new session keys may even be renegotiated during a chat session without the users knowing.

When a contact goes offline, the OTR session should be ended at both ends.  If one client does not know the other has gone offline (or knows, but does not end the OTR session) it will continue to send OTR encrypted messages that will never be able to be decrypted.

I believe Profanity has the correct behaviour here (ending the session when a client goes offline), but comment if you are seeing different behaviour.

If the your contact's client is not ending the session, then this issue is with their client.

If you reconnect and `/otr start` a new session, again the other end probably just continues as if nothing happened, since it didn't end the first session as it should.

Hope that makes sense.

**Comment by teran-mckinney** [comment]
Thank you. This is unfortunate for me but makes sense.

I appreciate your time!
