### ISSUE TITLE
The prof_whole_occurrences_tests unit test fails on all arches

### ISSUE THREAD

**Issue by sil2100** [boothj5/profanity#951]
While trying to resolve the armhf build failure on Ubuntu (as mentioned through #901), I have noticed that profanity no longer builds correctly at all on all architectures. Even with the 3 commits related to #901 cherry-picked into the current Ubuntu version (based on 0.5.0) the package fails to build because of a failure in prof_whole_occurrences_tests. It seems all of those test-cases which have any unicode characters in them are failing.

```
[ RUN      ] prof_whole_occurrences_tests
_lists_equal(prof_occurrences("我能吞下玻璃而", "我能吞下玻璃而", 0, TRUE, &actual), expected)
tests/unittests/test_common.c:448: error: Failure!
[  FAILED  ] prof_whole_occurrences_tests
```

Fully detailed build log can be found on my PPA build:
https://launchpadlibrarian.net/326893933/buildlog_ubuntu-artful-amd64.profanity_0.5.0-0.1ubuntu2~test1_BUILDING.txt.gz

The same test fails on all available architectures. I wonder if any change in the package dependencies could have caused such issues?

Thank you!

**Comment by diegoroversi** [comment]
Hello, 
   I think the problem is solved by this patch:
`--- a/tests/unittests/unittests.c
+++ b/tests/unittests/unittests.c
@@ -40,7 +40,8 @@
 #include "test_plugins_disco.h"
 
 int main(int argc, char* argv[]) {
-    setlocale(LC_ALL, "en_GB.UTF-8");
+    char *lc_all = setlocale(LC_ALL, "");
+    char *lc_ctype = setlocale(LC_CTYPE, NULL);
     char *codeset = nl_langinfo(CODESET);
     char *lang = getenv("LANG");
 
@@ -49,6 +50,12 @@ int main(int argc, char* argv[]) {
     if (lang) {
         printf("  LANG:       %s\n", lang);
     }
+    if (lc_all) {
+        printf("  LC_ALL      %s\n", lc_all);
+    }
+    if (lc_ctype) {
+        printf("  LC_CTYPE    %s\n", lc_ctype);
+    }
     if (codeset) {
         printf("  CODESET:    %s\n", codeset);
     }
`

Your build fails because the code set LC_ALL to "en_GB.UTF-8", but is probably this locale is missing on the build machines. 

This patch set the locale to what you set in your environment, so it should be there. I've added some more debug info.

**Comment by jubalh** [comment]
https://github.com/boothj5/profanity/commit/d52355d72ccbebfa82fd5b1166f8d9265ec4ff6c set the locale to en_GB.UTF-8. It was done due to https://github.com/boothj5/profanity/issues/901.

For the tests to work we need an UTF-8 locale installed and set on the testing machine. We needed to do this on the travis build too: https://github.com/boothj5/profanity/pull/1059/commits/0857b5ee4e40480cf9a3c543f93b5240f0d11b04

0.6.0 Debian tests for all archs look good: https://buildd.debian.org/status/logs.php?pkg=profanity&ver=0.6.0-1&suite=sid
