### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by Ejxqzgds** [boothj5/profanity#979]
If I see it correctly, the last release was in 2017-01. There are many bug fixes and improvements in master. Would you release a new officicial release soon? Thanks!

**Comment by HumanG33k** [comment]
Can you make a new official release ? (again sry) But some distro like Debian only use release.

**Comment by HumanG33k** [comment]
Ok thx :)

**Comment by jubalh** [comment]
https://github.com/boothj5/profanity/milestones

We plan to move some of the issues to 0.6.1 so that a release can happen earlier.

**Comment by pasis** [comment]
@jubalh, please, don't make release until I implement the feature that I promised here: https://groups.google.com/forum/#!topic/profanitydev/Nh5QhfVkmgc. It should be easy and quick.

**Comment by jubalh** [comment]
@pasis Sure. @boothj5 will create the release anyways :)

**Comment by pasis** [comment]
Ok, I've pushed the patch. But I've bumped into a bug and would be nice to have it fixed in 6.0. The issue with `/connect` when `/account` is configured. In this case all `/connect` options are ignored. Imagine, I have tls policy force in the account and I want to connect with the trust policy only in a particular moment. It would be more natural if `/connect` options had higher priority than `/account` ones.

**Comment by jubalh** [comment]
For reference: this is @pasis commit: https://github.com/boothj5/profanity/commit/7f65aaa9a2ba1e7d9fe182cc18938fa39462e095

Do you think a seperate bug report would be appropriate for what you found?

**Comment by pasis** [comment]
I've created #1021 in 0.6.0 milestone.

**Comment by jubalh** [comment]
Finally [0.6.0](https://github.com/boothj5/profanity/releases/tag/0.6.0) got released yesterday!
